name: Check Version Upgrade on PR

on:
  pull_request:
    branches:
      - main
    paths:
      - "package.json"

jobs:
  check_version_upgrade:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Get base branch version
        id: base_version
        run: |
          base_version=$(git show ${{ github.base_ref }}:package.json | jq -r .version)
          echo "base_version=$base_version" >> "$GITHUB_OUTPUT"

      - name: Get PR branch version
        id: pr_version
        run: |
          pr_version=$(cat package.json | jq -r .version)
          echo "pr_version=$pr_version" >> "$GITHUB_OUTPUT"

      - name: Compare versions
        run: |
          if [[ "$(echo "${{ steps.pr_version.outputs.pr_version }}" "${{ steps.base_version.outputs.base_version }}" | awk '{if ($1 <= $2) exit 1; exit 0}')" -eq 1 ]]; then
            echo "::error::Version in package.json has not been upgraded or is the same as the base branch."
            exit 1
          else
            echo "Version in package.json has been upgraded."
          fi
